---
networks:
  macvlan_network:
    external: true
    name: "${DOCKER_NETWORK}"

services:
  nginx:
    image: nginx:latest
    pull_policy: always
    container_name: radarr-nginx
    restart: always
    volumes:
      - "${NGINX}/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      macvlan_network:
        ipv4_address: "${IP_ADDRESS}"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    pull_policy: always
    container_name: radarr
    volumes:
      - "${RADARR_CONFIG}:/config"
      - "${MEDIA}:${ROOT_PATH}"
      - "${DOWNLOADS}:/downloads"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TIMEZONE}"
    restart: always
    network_mode: "service:nginx"
    depends_on:
      qbittorrent:
        condition: service_started

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    pull_policy: always
    container_name: radarr-qbittorrent
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TIMEZONE}"
      - "WEBUI_PORT=8080"
    restart: always
    network_mode: "service:nginx"
    volumes:
      - "${QBITTORRENT_CONFIG}:/config"
      - "${DOWNLOADS}:/downloads"
    depends_on:
      nginx:
        condition: service_started
