services:
  nginx:
    image: nginx:latest
    pull_policy: always
    container_name: radarr-nginx
    restart: always
    ports:
      - 9000:7878
      - 9001:8080

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    pull_policy: always
    container_name: radarr
    volumes:
      - "${RADARR_CONFIG}:/config"
      - "${MEDIA}:/${ROOT_PATH}"
      - "${DOWNLOADS}:/downloads"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TIMEZONE}"
    restart: always
    network_mode: "service:nginx"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    pull_policy: always
    container_name: radarr-qbittorrent
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TIMEZONE}"
      - "WEBUI_PORT=8080"
    restart: always
    network_mode: "service:nginx"
    volumes:
      - "${QBITTORRENT_CONFIG}:/config"
      - "${DOWNLOADS}:/downloads"